name: sync2gitee
# version: 1.0.1
# author: [yiXu](https://github.com/yi-Xu-0100)
# guide: [yi-Xu-0100/hub-mirror](https://github.com/yi-Xu-0100/hub-mirror)
# template: [sync2gitee.yml](https://github.com/yi-Xu-0100/hub-mirror/blob/main/template/sync2gitee.yml)
# lastmod: 2020-09-21 08:32:13

on:
  push:
  schedule:
    # UTC 17:00 -> CST (China) 1:00 see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '1 17 * * *'

jobs:
  run:
    name: Sync GitHub to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.4

      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/hub-mirror-action@v0.11
        with:
          src: github/yi-Xu-0100
          dst: gitee/yiXu0100
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: 'MY_REPO,Learn-for-coding'
          account_type: user
          force_update: true
